const message = {
    CREATED: "Created successfully",
    FETCHED: "Fetched successfully ",
    DISABLED: "Disabled successfully",
    ENABLE: "Enable successfully",
    UPDATED: "Updated Successfully!",
    LOGOUT: "User Logout Successfully!",
    NOT_FOUND: "Not found ",
    WENT_WRONG: "Somthing went wrong please contact to the admin",
    EMAIL_NOT_SENT: "EMail not sent, Please change Invoice Status to APPROVED",
    EMAIL_ALREADY_SENT: "EMail already sent to Customer",
    IS_EXIST: "Name already exist",
    IS_EMAIL_EXIST: "Email already exist", 
    SAGO_SERVER_SERVICE_ERROR_1 : "CODE_000001",
    SAGO_SERVER_SERVICE_ERROR_2 : "CODE_000002",
    NAME_AVAILABLE: "Name is available",
    ACCOUNT_DEACTIVATE: 'This account is deactivated',
    VENDOR_ALLOCATED: "Vendor allocated Successfully!",
    DUPLICATE_NAME_EMAIL : "Name or Email Exist",
    UN_AUTHORIZED : "Password does not match",
    SAGO_PULLING_SYNC : "Syncing is in progress.",
    SENT_SUCCESSFULLY: "Invoice Sent Successfully!",
    DOWN_LOAD: "Invoice Pdf Download Successfully!",
    PO_NOEXIST : " Po No. Already exist",
    NO_DATA_FOUND : "No data found",
    PO_NO_AVAILABLE: "Po No. is available",
    SERVER_ERROR: "Internal Server Error",
    FILE_NOT_FOUND: "File not found",
    SURVEY_RECONCILED: "Survey Reconciled Successfully!",
    FILE_SIZE: "File size should not more than 1 mb",
    FILE_NAME: "File name already exist",
    SURVEY_NOT_COMPLETED: "Survey is not completed ",
    PIDS_EXIST: "Survey PIDs are not exist",
    PID_UPLOADED: "Survey reconcile  pid uploaded successfully",
    SURVEY_STATUS_UPDATE: "Survey Status can not update",
    FILE_EXTENTION: "File is not a CSV file. Please upload csv file.",
    TRANSATION:'Transation Id is required',
    OPTION_ERROR:'Option data is Empty',
    PID_EXIST: "Client PIDs are does not exist ",
    PIDS_UPLOADED: "Client reconcile  pid uploaded successfully",
    CLIENT_RECONCILED: "Client Reconciled Successfully!",
    NO_ACCESS: 'You Have no permission to access this end point',
    FIRST_ROW: 'Your file format is not correct. Please download and check the sample file.',
    ROLE_EXITS: 'Role already exist',
    ROLE_AVAILABLE: "Role is available",
    PID_RECONCILED: 'PID already Reconciled',
    PID_ALREADY_DONE: 'Final Reconcilation for these PIDs is already Done.',
    NOT_CREATED: 'User Not Created',
    CREATED_SUCCESSFULLY: 'User Created Successfully.'
}
module.exports = { message }